"""empty message

Revision ID: 5c1265e509aa
Revises: 84adce3dfd17
Create Date: 2022-07-27 13:11:01.365228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1265e509aa'
down_revision = '84adce3dfd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('studentfee_cheque_date_key', 'studentfee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('studentfee_cheque_date_key', 'studentfee', ['cheque_date'])
    # ### end Alembic commands ###
