"""empty message

Revision ID: 19ec683a258b
Revises: 5c1265e509aa
Create Date: 2022-07-27 13:20:27.718676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ec683a258b'
down_revision = '5c1265e509aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentfee', sa.Column('bank', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentfee', 'bank')
    # ### end Alembic commands ###
