"""empty message

Revision ID: 84adce3dfd17
Revises: 926e0e1f859c
Create Date: 2022-07-27 12:45:19.081015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84adce3dfd17'
down_revision = '926e0e1f859c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentfee', 'bank')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentfee', sa.Column('bank', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
