"""empty message

Revision ID: e698e78b9c66
Revises: 19ec683a258b
Create Date: 2022-07-27 15:09:03.578103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e698e78b9c66'
down_revision = '19ec683a258b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('studentfee_active_key', 'studentfee', type_='unique')
    op.drop_constraint('studentfee_status_key', 'studentfee', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('studentfee_status_key', 'studentfee', ['status'])
    op.create_unique_constraint('studentfee_active_key', 'studentfee', ['active'])
    # ### end Alembic commands ###
